### ISSUE TITLE
HDR and bloom issues on mobile platforms

### ISSUE THREAD

**Issue by elringus** [Elringus/SpriteGlow#13]
Corresponding Unity issue: https://issuetracker.unity3d.com/issues/bloom-not-working-with-hdr-and-bloom-threshold-at-1 

Even though it's marked as fixed in 2017.1, it's actually not.

Workaround: unknown, please share if you find any solution.

**Comment by hlibr** [comment]
I've contacted Unity regarding this issue and they got back to me with a working solution:

By default "Use HDR" (the project wide setting) is disabled for all graphics tiers on iOS and Android. To enable it please go to "Edit > Project Settings > Graphics" and disable "Use Defaults" on the tiers where you wish to use HDR. Then enable the "Use HDR' checkbox on these tiers.

Seems that you also have to set the shader quality to high, otherwise the SpriteOutline shader fails to compile.

**Comment by elringus** [comment]
Thank you for finding this out! Looks like it appeared to be a feature rather than a bug :) I’ve added the info about enabling HDR for graphic tiers to the [readme](https://github.com/Elringus/SpriteGlow#why-the-glow-doesnt-appear). 

About the compilation issue: I’ve just tested builds on both low and medium shader quality for Android/iOS and everything seems to work fine. Could it be you’ve worked with an old SpriteGlow version or used some special setup? Please consider creating a new issue for this case (if it’s still relevant).

**Comment by hlibr** [comment]
Yep, the shader compilation error was related to me using an older version, thanks.
